name: 'Install ninja-build tool'
description: 'Installs ninja and adds it to the path'
branding:
  icon: 'terminal'
  color: 'white'
inputs:
  version:
    description: 'Version of ninja-build to install'
    default: '1.10.2'
    required: true
  platform:
    description: 'Override default platform with one of [win, mac, linux]'
    required: false
  destination:
    description: 'Destination directory, will be added to PATH'
    default: 'ninja-build'
    required: false
  http_proxy:
    description: 'Proxy server'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
